import Head from "next/head";
import { StoreProvider } from "../context/store-context";
import { DisplayProvider } from "../context/display-context";
import "../styles/globals.css";
import Layout from "../components/layout/layout";
import 'bootstrap/dist/css/bootstrap.css'

function MyApp({ Component, pageProps }) {
  return (
    <StoreProvider>
      <DisplayProvider>
        <Head>
          <title>Bookoe</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/assets/images/logo512.png" />
        </Head>
        <Layout>
          <Component {...pageProps} />
        </Layout>
      </DisplayProvider>
    </StoreProvider>
  );
}

export default MyApp;
